image: node:10.3.0

# - test
stages:
  - deps
  - deploy

# before_script:
#   - yarn

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

get-deps:
  stage: deps
  script:
    - yarn

run-unit-test:
  stage: test
  script:
    - yarn test

deploy-staging:
  stage: deploy
  script:
    - yarn ci:deploy:staging
  only:
    - staging
    - merge_requests

deploy-production:
  stage: deploy
  script:
    - yarn ci:deploy:prod
  only:
    - master
    - merge_requests
